### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by bartjkdp** [Quixote-project/concierge#37]
As this now is not a Pleio-only project any more, It would be nice to come up with a new name for this project. Some (not so good) suggestions:

- doorkeeper
- safeguard
- officer
- myaccount

Also would be nice to move it over to the Quixote-project organization in a while.

**Comment by markwooff** [comment]
I like **doorkeeper** as a name, reflects the fact that this service will be determining what the user will have access to. Here are another few ideas that came to mind:

- entryway
- pathway
- accessly
- kick**access** (lol)
- **key**store
- **key**role

**Comment by ToferC** [comment]
Maybe because we're Canadian, what about things that welcome people in vs.
Keep them out:

- butler
- doorbell
- maitre-d
- concierge
- portal
- threshold
- archway

We could add django-* if need be.

**Comment by bartjkdp** [comment]
I think i like concierge!

**Comment by bartjkdp** [comment]
We settled on concierge!
